"""Added notification read status

Revision ID: 3b137930d1c1
Revises: a3c56290c82c
Create Date: 2026-06-03 10:57:10.316143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b137930d1c1'
down_revision = 'a3c56290c82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
